name: Build and Deploy

on:
  push:
    branches:
      - rewrite

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        VUE_APP_LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        VUE_APP_LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: dist
