name: Build and Deploy

on:
  push:
    branches:
      - rewrite

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false 

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        VUE_APP_LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        VUE_APP_LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
