name: Build and Deploy

on:
  push:
    branches:
      - rewrite

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Store variables
      run: |
        touch .env
        VUE_APP_LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }} >> .env
        VUE_APP_LASTFM_API_SECRET=${{ secrets.LASTFM_API_SECRET }} >> .env

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: dist
